config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  scope :find_newest_article, -> { order(created_at: :desc).limit(5) }

  validates :name, presence: :true, length: { maximum: 50 }
  validates :category, presence: :true, length: { maximum: 50 }
  validates :detail, presence: :true, length: { maximum: 1000}
  validates :lowest_price, presence: :true, length: { maximum: 20}

end


# name, :lowest_price, :detail, :user_id, :category

# http://www.ken-tmr.com/sketch-201503/paris-5.jpg

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [ :show, :edit, :update, :destroy]
  def index
    @q = Product.all.order(created_at: :desc).ransack(params[:q])
    @products = @q.result.page(params[:page]).per(20)
    @new_products = Product.order(create_at: :desc).limit(5)
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: '投稿に成功しました。'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: '更新に成功しました'
    else
      render
    end
  end

  def destroy
    @Product.destroy
    redirect_to "/posts"
  end


  private

  def product_params
    params.require(:product).permit(:name, :lowest_price, :detail, :user_id, :category)
  end

  def set_product
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'PumpeeArts', products_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'トップページ', products_path %></li>
        <li><a href="/product/new">新規投稿</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/user">サインアップ</a></li>
        <li><a href="/user">ログイン</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PumpeeArts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>



</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
    <% if notice.present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= notice %></p>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= alert %></p>
    </div>
  <% end %>



  <%= yield %>
</div>

</body>
</html>

app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>出品</h1>
    <% if @product.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <div id="error_explanation">
          <h2><%= @product.errors.count %>件のエラーがあります。</h2>
          <ul>
          <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>


    <%= form_for @product do |f| %>
      <div class="form-group">
        <%= f.label "作品名" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "カテゴリ" %>
        <%= f.text_field :category, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "詳細" %>
        <%= f.text_area :detail, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "最低価格" %>
        <%= f.text_field :lowest_price, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "イメージ画像" %>
        <%= f.text_field :image_url, class: "form-control" %>
      </div>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>ブログ記事編集</h1>
    <%= render 'form' %>
  </div>
</div>
<div class="col-md-12">
  <h1>編集</h1>
  <%= form_for @product do |f| %>
    <div class="form-group">
      <%= f.label "作品名" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "カテゴリ" %>
      <%= f.text_field :category, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "詳細" %>
      <%= f.text_area :detail, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "最低価格" %>
      <%= f.text_field :lowest_price, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "イメージ画像" %>
      <%= f.text_field :image_url, class: "form-control" %>
    </div>
    <%= f.submit '編集する', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="col-md-12">
  <div class="form-inline pull-right" style="margin-bottom:10px;">
    <%= search_form_for @q do |f| %>
      <div class="form-group">
        <%= f.search_field :name_or_detail_cont, placeholder: "ジャンル、キーワードを検索", class: "form-control" %>
        <%= f.submit "検索", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>
<div class="row">

  <div class="col-md-8">
    <% @products.each do |product| %>
      <div class="article">
        <h2>作品名：<%= product.name %></h2>
        <p>カテゴリ：<%= product.category %></p>
        <p>作成日：<%= product.created_at %></p>
        <p><%= truncate(product.detail, length: 50) %></p>
        <p><%= link_to "詳細を見る", product, class: "btn btns-default" %></p>
      </div>
    <% end %>
    <%= paginate @products %>
  </div>

  <div class="col-md-4">
   <% if User.exists? %>
    <div class="thumbnail">
      <%= image_tag User.first.image_url, alt: "ユーザーアイコン" %>
      <div class="caption">
        <h3>ユーザー名：<%= User.first.name %></h3>
        <p>詳細：<%= User.first.description %></p>
      </div>
    </div>
    <% end %>
    <div class="list-group">
    <% if User.exists? %>
      <% @product.each_with_index do |product, index| %>
      <% if index >= 5
           break
         end
      %>
      <%= link_to product.name, product, class: "list-group-item" %>
      <% end %>
      <% end %>
    </div>
  </div>

</div>

app/views/products/new.html.erb
<div class="row">
  <div class="col-md-12">
      <%= render 'form' %>
  </div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1><%= @product.name %></h1>
    <p>カテゴリ: <%= @product.category %></p>
    <p>投稿日:<%= @product.created_at %></p>
    <hr>
    <p>
      <%= simple_format(@product.detail) %>
    </p>
    <hr>
    <%= link_to "編集", edit_product_path(@product), class: "btn btn-default" %>
    <%= link_to "削除", product_path(@product), class: "btn btn-default", method: :delete %>
  </div>
</div>